Output ./demo.gif

Set Shell nu

Set FontFamily 'Hasklug NF'

Set FontSize 18
Set Width 800
Set Height 600

Hide
Type "use ~/dotfiles/secrets/openai.nu"
Enter
Type "nvim"
Enter
Sleep 500ms
Show

Set TypingSpeed 140ms

Type "iCount to three"
Ctrl+c
Type "V:Llm"
Enter
Sleep 500ms
Type "Go"
Enter
Type "// fizzbuzz in javascript"
Enter
Type "function fizz"
Ctrl+c
Ctrl+c
Type "vk^:Llm"
Enter
Sleep 5s
Type "kko"
Enter
Type "-- fizzbuzz in lua"
Enter
Type "functi"
Ctrl+c
Ctrl+c
Type "vk^:Llm"
Enter
Sleep 5s
Type "jjjjjjjjjjjj"
Type "G"
Sleep 2s
Type "kkkkkkkkkkkk"
Sleep 8s
