name: Checks

on:
  push:
    branches:
      - main
      - gha-selene-check
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run plenary tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
      - name: setup plenary
        run: |
          mkdir -p ~/.local/share/nvim/site/pack/vendor/start
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
          ln -s $(pwd) ~/.local/share/nvim/site/pack/vendor/start
      - name: run tests
        run: make test
  lint:
    name: Lint with selene and stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.19.1
          args: --color always --check .
      - uses: NTBBloodbath/selene-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --display-style=quiet .
          version: 0.26.1
  types:
    name: Check types with luals
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: gsuuon/nvim-typecheck-action@annotate
        with:
          path: lua/model
          configpath: .luarc.json
          luals-version: 3.7.4
          annotate: true
